apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-prune-resources
  namespace: k8s-pruner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-pruner
subjects:
- kind: ServiceAccount
  name: sa-prune-resources
  namespace: k8s-pruner
roleRef:
  kind: ClusterRole
  name: reader
  apiGroup: rbac.authorization.k8s.io


